### ISSUE TITLE
Some memory improvements

### ISSUE THREAD

**Issue by martimunicoy** [anasf97/PELEpharmacophore#12]
There is a potential memory leak in: https://github.com/anasf97/PELEpharmacophore/blob/167f0ebd7185a091055b0dcca70f068dafb36815/PELEpharmacophore/helpers.py#L73

Something like would be better:
```python
with Pool(n_workers) as p:
    output = p.map(f, iterable)

return output
```

**Comment by anasf97** [comment]
Fixed in https://github.com/anasf97/PELEpharmacophore/commit/48f681343f14ac9a9eb222d85a840cd668545867. Thanks for reviewing! :)
