### ISSUE TITLE
Mean shift algorithm to detect the pharmacophore features

### ISSUE THREAD

**Issue by martimunicoy** [anasf97/PELEpharmacophore#4]
# Description
I think that the [MeanShift algorithm](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.MeanShift.html) is a nice candidate to be supported as an alternative method to the current grid-based approach. It would locate the most populated regions according to the centroid of the closest neighbours and it could be a more flexible and sensitive approach compared to the 3D grid.

# Solution
An example of how to use the MeanShift algorithm from the Scikit Learn Python library:
```python
from sklearn.cluster import MeanShift
estimator = MeanShift(bandwidth=1,
                      n_jobs=number_of_processors,
                      cluster_all=True)
results = estimator.fit_predict(coordinates)

# Get centroids and number of clusters
centroids = estimator.cluster_centers_
n_clusters = len(centroids)
```

**Comment by anasf97** [comment]
Implemented in commit https://github.com/anasf97/PELEpharmacophore/commit/3e2d34d13561f1d152c4091e483a6497c51cdf88
